"use client";

import { useRouter, useSearchParams } from "next/navigation";
import { Suspense, useState } from "react";
import { apiFetch } from "@/lib/api";
import type { GeneratedStrategyDraft, Strategy } from "@/lib/types";

const GENERATED_STRATEGY_DRAFT_KEY = "rewind.generatedStrategyDraft.v1";

const DEFAULT_CODE = `from engine.strategy import Strategy
from engine.signal import Signal


class MyStrategy(Strategy):
    def init(self, params):
        pass

    def next(self, row, portfolio):
        return None
`;

export default function NewStrategyPage() {
  return (
    <Suspense
      fallback={
        <div className="mx-auto w-full max-w-4xl px-6 py-10 text-sm text-zinc-400">
          Loading strategy editor...
        </div>
      }
    >
      <NewStrategyPageClient />
    </Suspense>
  );
}

function isGeneratedStrategyDraft(value: unknown): value is GeneratedStrategyDraft {
  if (!value || typeof value !== "object") return false;
  const record = value as Record<string, unknown>;

  return (
    typeof record.code === "string" &&
    (typeof record.className === "string" || record.className === null) &&
    typeof record.sourceMessageId === "string" &&
    typeof record.createdAt === "string"
  );
}

function loadGeneratedDraft(draftParam: string | null): {
  draft: GeneratedStrategyDraft | null;
  error: string;
} {
  if (draftParam !== "generated") return { draft: null, error: "" };
  if (typeof window === "undefined") return { draft: null, error: "" };

  try {
    const storedDraft = sessionStorage.getItem(GENERATED_STRATEGY_DRAFT_KEY);
    if (!storedDraft) return { draft: null, error: "Generated strategy draft was not found." };

    const parsedDraft = JSON.parse(storedDraft) as unknown;
    if (!isGeneratedStrategyDraft(parsedDraft)) {
      return { draft: null, error: "Generated strategy draft is invalid." };
    }

    return { draft: parsedDraft, error: "" };
  } catch {
    return { draft: null, error: "Generated strategy draft could not be loaded." };
  }
}

function NewStrategyPageClient() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const draftParam = searchParams.get("draft");
  const [initialDraft] = useState(() => loadGeneratedDraft(draftParam));
  const [name, setName] = useState(
    initialDraft.draft ? initialDraft.draft.className ?? "GeneratedStrategy" : ""
  );
  const [description, setDescription] = useState(
    initialDraft.draft ? "Generated by Rewind chat. Review before running." : ""
  );
  const [code, setCode] = useState(initialDraft.draft?.code ?? DEFAULT_CODE);
  const [generatedDraft, setGeneratedDraft] = useState<GeneratedStrategyDraft | null>(
    initialDraft.draft
  );
  const [draftError, setDraftError] = useState(initialDraft.error);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setSubmitting(true);
    setError("");

    try {
      const strategy = await apiFetch<Strategy>("/api/v1/strategies", {
        method: "POST",
        body: JSON.stringify({ name, description, code }),
      });
      if (generatedDraft) {
        sessionStorage.removeItem(GENERATED_STRATEGY_DRAFT_KEY);
      }
      router.push(`/strategies/${strategy.id}`);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to create strategy");
      setSubmitting(false);
    }
  }

  function discardGeneratedDraft() {
    sessionStorage.removeItem(GENERATED_STRATEGY_DRAFT_KEY);
    setGeneratedDraft(null);
    setDraftError("");
    setCode(DEFAULT_CODE);
    router.replace("/strategies/new", { scroll: false });
  }

  return (
    <div className="mx-auto w-full max-w-4xl px-6 py-10">
      <h1 className="text-2xl font-bold">New Strategy</h1>

      {generatedDraft ? (
        <div className="mt-6 rounded border border-blue-800 bg-blue-950/30 p-4 text-sm">
          <div className="flex flex-wrap items-start justify-between gap-3">
            <div>
              <p className="font-medium text-blue-200">Generated strategy draft</p>
              <p className="mt-1 text-zinc-400">
                Review and edit the code before creating the strategy.
              </p>
              <p className="mt-1 text-xs text-zinc-500">
                Source message {generatedDraft.sourceMessageId.slice(0, 8)}... -{" "}
                {new Date(generatedDraft.createdAt).toLocaleString()}
              </p>
            </div>
            <button
              type="button"
              onClick={discardGeneratedDraft}
              className="rounded border border-zinc-700 px-3 py-1.5 text-sm text-zinc-300 hover:bg-zinc-800"
            >
              Discard draft
            </button>
          </div>
        </div>
      ) : null}

      {draftError ? (
        <p className="mt-6 rounded border border-red-800 bg-red-950 px-3 py-2 text-sm text-red-300">
          {draftError}
        </p>
      ) : null}

      <form onSubmit={handleSubmit} className="mt-8 space-y-6">
        <div>
          <label className="block text-sm font-medium text-zinc-300">Name</label>
          <input
            type="text"
            required
            value={name}
            onChange={(e) => setName(e.target.value)}
            className="mt-1 w-full rounded border border-zinc-700 bg-zinc-900 px-3 py-2 text-sm text-zinc-100 focus:border-blue-500 focus:outline-none"
            placeholder="e.g. BuyAndHold"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-zinc-300">Description</label>
          <input
            type="text"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            className="mt-1 w-full rounded border border-zinc-700 bg-zinc-900 px-3 py-2 text-sm text-zinc-100 focus:border-blue-500 focus:outline-none"
            placeholder="Brief description of the strategy"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-zinc-300">Code</label>
          <textarea
            required
            value={code}
            onChange={(e) => setCode(e.target.value)}
            rows={20}
            className="mt-1 w-full rounded border border-zinc-700 bg-zinc-900 px-3 py-2 font-mono text-sm text-zinc-100 focus:border-blue-500 focus:outline-none"
            spellCheck={false}
          />
        </div>

        {error && <p className="text-sm text-red-400">{error}</p>}

        <button
          type="submit"
          disabled={submitting}
          className="rounded bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-500 disabled:opacity-50"
        >
          {submitting ? "Creating..." : "Create Strategy"}
        </button>
      </form>
    </div>
  );
}
